name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops-project
            git pull
            sudo docker build -t my-devops-site .
            sudo docker stop my-site || true
            sudo docker rm my-site || true
            sudo docker run -d -p 80:80 --name my-site my-devops-site
