name: Docker Build Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-devops-site .
