name: Docker Build Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-devops-site .

      - name: Run container
        run: docker run -d -p 8080:80 --name test-site my-devops-site

      - name: Wait for Nginx
        run: sleep 5

      - name: Test website
        run: curl http://localhost:8080
